### PR TITLE
Implementation of Classes and Associations for School Library

### PR DESCRIPTION
**Pull request by Alejandroq12**
Hello, dear reviewer.

I kindly request your review on the implementation of the required classes and their associations for my project. This pull request contains the following changes:

- **Classroom Class**: A new class `Classroom` was created with the `@label` instance variable and its getter and setter. It also implements a has-many/belongs-to relationship with the `Student` class.
  
- **Student Class**: The `Student` class was updated to inherit from `Person` and belongs to a `Classroom`. It also sets the classroom when a student is added to a classroom and vice versa.
  
- **Book Class**: A new `Book` class was created with `@title` and `@author` instance variables. A has-many association was implemented with the `Rental` class.
  
- **Rental Class**: A new `Rental` class was created with `@date` instance variable. It has a many-to-many association with `Book` and `Person` classes using the Rental class as an intermediary.
  
- **Person Class**: The `Person` class was updated to have a has-many association with the `Rental` class.
  
All the classes were implemented following the project specifications and Ruby best practices. I also took care to ensure that the changes would not break any existing functionality.

To test the project, you can run the main file in the root directory of the project using the command line. It will demonstrate the functionality of the implemented classes and associations.

I'm looking forward to receiving your valuable feedback.

Thank you,

Julio Quezada.

### CODE REVIEW

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @Alejandroq12, 

# Required Changes ♻️

so-close-jim-halpert

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 
- Correct associations ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandroq12** [comment]
Thank you very much for your excellent feedback. I will work on it.

**Review by anagudelogu — APPROVED** [review]
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @Alejandroq12, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 



## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandroq12** [comment]
Thank you very much for your time.
Have a great day.

**Pull request merged**
